---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninjin-deployment
  labels:
    app: ninjin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninjin
  template:
    metadata:
      labels:
        app: ninjin
    spec:
      containers:
      - name: ninjin
        image: ghcr.io/sohosai/ninjin:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ninjin-service
spec:
  selector:
    app: ninjin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
